name: Use Composite Action

on:
    push:
        branches: [main]

jobs: 
    greet: 
        runs-on: ubuntu-latest
    
        steps:

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Run Custom Composite Action
              id: greet_step
              uses: ./.github/actions/setup-and-greet
              with:
                name: "Rahul"
                language: "hi"

            - name: Print Output
              run: echo "Greeted value is ${{ steps.greet_step.outputs.greeted }}"