name: Secrets Demo

on:
    push:
        branches: [main]

jobs: 

    Secrets-check:
        runs-on: ubuntu-latest

        steps:
            
            - name: Check if secrets exits
              run: echo "The secret is set true"

            - name: Printing Secrets Value
              run: echo "The secrets value is ${{ secrets.MY_SECRET_MESSAGE }}"

    #Task 2
    secrets-env:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Use Secrets as Environment Variable
              env:
                username: ${{ secrets.DOCKER_USERNAME }}
                token: ${{ secrets.DOCKER_TOKEN }}
              run: |
                echo "Docker Username and Token is set "
                if [ -n "$username" ]; then
                    echo "Username is available"
                fi
                if [ -n "$token" ]; then
                    echo "Token is available"
                fi
              