name: Secrets Demo

on:
    push:
        branches: [main]

jobs: 

    Secrets-check:
        runs-on: ubuntu-latest

        steps:

            - name: Check if secrets exits
              run: echo "The secret is set true"

            - name: Printing Secrets Value
              run: echo "The secrets value is ${{ secrets.MY_SECRET_MESSAGE }}"

    #Task 2
    secrets-env:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Use Secrets as Environment Variable
              env:
                username: ${{ secrets.DOCKER_USERNAME }}
                token: ${{ secrets.DOCKER_TOKEN }}
              run: |
                echo "Docker Username and Token is set "
                if [ -n "$username" ]; then
                    echo "Username is available"
                fi
                if [ -n "$token" ]; then
                    echo "Token is available"
                fi
    
    #Task 3
    upload-artifact:
        runs-on: ubuntu-latest

        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Create a Repost file
              run: |
                mkdir -p reports
                echo "Test result: All test passed successfully on $(date)" > reports/test-report.txt
                echo "Log entry: Workflow run started " >> reports/app.log
                echo "Log entry: Workflow run completed" >> reports/app.log
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: workflow-artifact
                path: reports/
    
    #Task4
    download-artifact:
        runs-on: ubuntu-latest
        needs: upload-artifact

        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with: 
                name: workflow-artifact
            
            - name: Print Artifact
              run: cat workflow-artifact/reports/test-report.txt
