name: Smart Trigger - Code Changes Only

on:
  push:
    branches:
      - main
      - 'release/*'
    paths:
      - 'src/**'
      - 'app/**'

jobs:
  run-on-code-change:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Code changed in src/ or app/"