name: Secrets Demo

on:
    push:
        branches: [main]

jobs: 

    Secrets-check:
        runs-on: ubuntu-latest

        steps:
            - name: Check if secrets exits
              run: echo "The secret is set true"

            - name: Printing Secrets Value
              run: echo "The secrets value is ${{ secrets.MY_SECRET_MESSAGE }}"