name: Conditionals Example

on:
  push:
    branches: [main]
  pull_request:

jobs:

  conditional-job:
    runs-on: ubuntu-latest

    # Job runs only on push events
    if: github.event_name == 'push'

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run only on main branch
        if: github.ref == 'refs/heads/main'
        run: echo "This step runs only on the main branch"

      - name: Intentional failure step
        run: echo "Not failed"

      - name: Run if previous step failed
        if: failure()
        run: echo "Previous step failed, so this step is running"

      - name: Step with continue-on-error
        continue-on-error: true
        run: |
          echo "This step will fail but workflow will continue"
          exit 1

      - name: Step after error
        run: echo "Workflow continues even after the error"
        