name: Manual Trigger
on:
    workflow_dispatch:
        inputs:
            environments:
                description: This is the environment where this workflow runs
                default: 'staging'
                required: true              
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Manul Trigger
              run: echo "Enabled Manul Trigger"
